import { ArrowLeft, Check, ChevronRight, CircleAlert, ExternalLink } from 'lucide-react'
import { ImpactNode, RiskBadge, SectionHeading, StatusBadge } from '../components/ui'

export default function AnalysisResultsPage({ analysis, onBack, onNavigate }) {
  return <div className="page-content results-page"><div className="result-top"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Back to analyses</button><div className="result-actions"><button className="button ghost">Export report <ExternalLink size={14} /></button><button className="button primary" onClick={() => onNavigate('analyze')}>New analysis</button></div></div>
    <div className="result-heading"><div><span className="eyebrow">Analysis #{analysis.id} / Completed {analysis.timestamp}</span><h1>{analysis.change}</h1><div className="result-meta"><span>{analysis.repository}</span><span>{analysis.branch}</span><span>Mock result</span></div></div><RiskBadge risk={analysis.overallRisk} /></div>
    <section className="summary-strip">{analysis.summary.map(([label, value, detail]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>)}</section>
    <section className="panel impact-map-panel"><SectionHeading eyebrow="Dependency surface" title="Impact map" action={<span className="muted-label">5 relationship layers</span>} /><div className="impact-map"><ImpactNode label="Changed component" value="AuthProvider" tone="cyan" /><ImpactNode label="Affected services" value="API Gateway · User Service" tone="blue" /><ImpactNode label="Affected modules" value="Session · Permissions · Billing" tone="amber" /><ImpactNode label="Affected tests" value="18 recommended tests" tone="green" last /></div></section>
    <div className="results-grid"><section className="panel"><SectionHeading eyebrow="Signal review" title="Risk analysis" />{analysis.risks.map((risk) => <div className="risk-row" key={risk.title}><div className={`risk-score ${risk.tone}`}><strong>{risk.score}</strong><span>/100</span></div><div className="risk-copy"><div><strong>{risk.title}</strong><StatusBadge tone={risk.tone}>{risk.status}</StatusBadge></div><p>{risk.description}</p><div className="risk-bar"><span className={risk.tone} style={{ width: `${risk.score}%` }} /></div></div></div>)}</section><section className="panel readiness-panel"><SectionHeading eyebrow="Go / no-go" title="Release readiness" /><div className="readiness-status"><CircleAlert size={20} /><div><strong>Review needed</strong><span>Not ready to ship</span></div></div><div className="readiness-block"><span>Why</span><p>High architecture and security risk requires validation of the new identity boundary.</p></div><div className="readiness-block"><span>Blocking issues</span><p>OAuth callback tests are not yet passing in the current branch.</p></div><div className="readiness-block"><span>Recommended actions</span><p>Run P0 tests, verify redirect allowlists, and get platform security sign-off.</p></div><button className="button secondary full-button" onClick={() => onNavigate('tests')}>View recommended tests <ChevronRight size={15} /></button></section></div>
    <div className="results-grid lower-grid"><section className="panel"><SectionHeading eyebrow="Repository surface" title="Affected files" /><div className="table-scroll"><table><thead><tr><th>File</th><th>Type</th><th>Impact</th><th>Reason</th></tr></thead><tbody>{analysis.files.map(([file, type, impact, reason]) => <tr key={file}><td><code className="file-code">{file}</code></td><td className="muted-cell">{type}</td><td><RiskBadge risk={impact} /></td><td className="muted-cell">{reason}</td></tr>)}</tbody></table></div></section><section className="panel"><SectionHeading eyebrow="Coverage plan" title="Recommended tests" /><div className="test-list">{analysis.tests.map((test) => <div className="test-item" key={test.name}><span className="test-check"><Check size={13} /></span><div><strong>{test.name}</strong><p>{test.reason}</p></div><StatusBadge tone={test.priority === 'P0' ? 'red' : 'amber'}>{test.priority}</StatusBadge></div>)}</div></section></div>
  </div>
}
